### ISSUE TITLE
Create markdown document (linked to from README) about how to Fork your own CallParty

### ISSUE THREAD

**Issue by mhfowler** [CallParty/CallParty#108]
our README is primarily direct at on-boarding contributors who want to help with the callparty deployment 

in the future we may want a document which describes how you would
- fork our codebase
- setup your own deployment infrastructure
- run your own callparty

**Comment by jayres** [comment]
I think this was partially if not mostly solved with the recent docs changes. We can always open new issues if this is unsatisfactory to open source users.
