### ISSUE TITLE
If you are the first caller, say something more inspiring then we've had 0 calls so far

### ISSUE THREAD

**Issue by mhfowler** [CallParty/CallParty#110]

**Comment by kelseyah** [comment]
@o0oo00o0o is writing up a new thing for this, to replace "Woo thanks for your work! We’ve had 0 other calls so far. We’ll reach out when we have updates and an outcome on the issue."

**Comment by o0oo00o0o** [comment]
How dis?

"Congrats, you’re the first caller on this issue! You’ve joined the ranks of other famous firsts in American History. We'll reach out when we have updates and an outcome on the issue."

**Comment by jayres** [comment]
Conversation easing response #142

**Comment by mhfowler** [comment]
I think its kind of funny but also kind of confusingly self-deprecating to make this joke. Like someone isn't going to be in a history book by making a phone call... but I do think that engaging in activism is creating history and maybe that's something not to dismiss in a joke.  I know I made the joke originally lol y'all have done a great job  writing and doing bot persona feel free to ignore me
