### ISSUE TITLE
actionDescription is returning "undefined"

### ISSUE THREAD

**Issue by kelseyah** [CallParty/CallParty#126]
This was the input in the admin form: "lots of bad stuff happening because bad stuff happens and we have until Wednesday to stop it"

This was the result for the user:
<img width="214" alt="screen shot 2017-02-20 at 8 24 56 pm" src="https://cloud.githubusercontent.com/assets/3522339/23147150/ab5c4de8-f7aa-11e6-8f9e-5b6b22130d51.png">

**Comment by jayres** [comment]
The issue here is that the description doesn't lie in the `campaignAction`, but in the actual `campaign`. We need to bring that information into the `campaignAction` so that it can be referenced.

**Comment by jayres** [comment]
Description bug #146

**Comment by kelseyah** [comment]
@jayres no longer seeing 'undefined' but it's still not pulling the right content. Should be pulling issueMessage from the admin panel.

Example – I just sent "lots of bad stuff happening because bad stuff happens and we have until Wednesday to stop it" and received "This is a test" instead.

Sent:
<img width="508" alt="screen shot 2017-02-27 at 3 53 59 pm" src="https://cloud.githubusercontent.com/assets/3522339/23379447/fbab1108-fd04-11e6-9a41-b00b5e5546a4.png">

Received:
<img width="224" alt="screen shot 2017-02-27 at 3 53 41 pm" src="https://cloud.githubusercontent.com/assets/3522339/23379436/eebdf83e-fd04-11e6-8b3e-1f1b3000c70d.png">

**Comment by mhfowler** [comment]
im gonna take a look at this now as im here waitin for oren to finish something

**Comment by mhfowler** [comment]
@kelseyah super tiny fix. you can test it on staging now
