### ISSUE TITLE
Fix preview positioning so it doesn't go past the bottom of the page

### ISSUE THREAD

**Issue by kelseyah** [CallParty/CallParty#131]

**Comment by jayres** [comment]
<img width="1262" alt="screen shot 2017-03-26 at 3 27 14 pm" src="https://cloud.githubusercontent.com/assets/8247248/24334477/d634cfba-1238-11e7-8e92-52b1472bd687.png">

**Comment by jayres** [comment]
Will be fixed in Frontend tweaks #226

**Comment by jayres** [comment]
This was fixed with the frontend changes two weeks ago!
