### ISSUE TITLE
Bot shouldn't respond a user that responds to the last message the bot sends in any script

### ISSUE THREAD

**Issue by kelseyah** [CallParty/CallParty#132]
<img width="252" alt="screen shot 2017-02-20 at 8 33 04 pm" src="https://cloud.githubusercontent.com/assets/3522339/23147301/d762518e-f7ab-11e6-9d75-1a8bbe488ed0.png">

**Comment by jayres** [comment]
Maybe we do a regex for question marks AND do a thing where we check character count to exclude common greetings. Something like 11 characters or above we send that message to? It will prevent a lot of the common responses that have no real context like "cool," "thanks," or "cool. thanks!"

**Comment by kelseyah** [comment]
cc/ @oshoham

**Comment by kelseyah** [comment]
Phrases:

Bye
Thank u
Thanks (starts or ends with)
Thank you (starts or ends with)
Sounds good
👍
cool
thankssss
ok
okay
yay
thumbs up
kk
excellent
