### ISSUE TITLE
Fix formatting in last message of Call to Action

### ISSUE THREAD

**Issue by kelseyah** [CallParty/CallParty#133]
Split the existing bubble into two messages: 
1 – "Woo thanks for your work! We’ve had 0 calls so far. We’ll reach out when we have updates and an outcome on the issue."
2 – "Share this action with your friends to make it a party [shareURL]"

(current:)
<img width="242" alt="screen shot 2017-02-20 at 8 34 44 pm" src="https://cloud.githubusercontent.com/assets/3522339/23147401/a3bd6566-f7ac-11e6-97b3-0cfff94a9871.png">

**Comment by jayres** [comment]
Conversation easing response #142
