### ISSUE TITLE
In the callConvo ask the user if they're ready to call before sending the rest of the convo

### ISSUE THREAD

**Issue by kelseyah** [CallParty/CallParty#141]
After sending the issueMessage and issueLink, use a [Facebook Button Template](https://developers.facebook.com/docs/messenger-platform/send-api-reference/button-template) to ask the user if they're ready, before sending the information about who they're calling and the issueAction.

template_type = button
text = "What do you wanna do?",
buttons = 
Call now
Remind me later
I don't wanna do this

If the user chooses "Call Now" we send them the rest of the convo

If the user chooses "Remind me later" we send them the rest of the convo in 4 hours

If the user chooses "I don't wanna do this" we say "That's ok! We'll let you know when there's another issue to call about"

assigning to Andrew for better copy!

**Comment by o0oo00o0o** [comment]
Cleaned up copy:

template_type = button
text = "Are you ready to call now?",
buttons =
Yes, I'm ready
Remind me later
I don't want to call

If the user chooses "Yes, I'm Ready" we send them the rest of the convo

If the user chooses "Remind me later" we send them the rest of the convo in 4 hours

If the user chooses "I don't want to call" we say, "That's okay! We'll let you know when there's another issue to call about. To help with future issues, please tell us why."

**Comment by o0oo00o0o** [comment]
A slight change:

template_type = button
text = "Are you ready to call now?",
buttons =
Yes, I'm ready
Remind me later
I don't want to call

If the user chooses "Yes, I'm Ready" we send them the rest of the convo

If the user chooses "Remind me later" we send them the rest of the convo in 4 hours

If the user chooses "I don't want to call" we say, "That's okay! Want to tell me about it?"

User states reason. We say, "Thanks for telling me. I'll let you know when there's another issue to call about."

**Comment by kelseyah** [comment]
Few tweaks for v1, taking remind me later out as a separate issue. Some copy changes below:

template_type = button
text = "Are you ready to call now?",
buttons =
Yes, I'm ready
I don't want to call

If the user chooses "Yes, I'm Ready" we send them the rest of the convo

If the user chooses "I don't want to call" we say, "That's okay! Want to tell me why?"

User states reason. We say, "Got it – I'll let you know when there's another issue to call about."
