### ISSUE TITLE
callConvo isn't responding when user tells it what went wrong in callConvo

### ISSUE THREAD

**Issue by kelseyah** [CallParty/CallParty#155]
User chooses "something went wrong > Bot asks "want to tell me about it? > User enters message > Bot should respond but isn't

**Comment by mhfowler** [comment]
@kelseyah just fixed this. In general, would you prefer I just close bug tickets when I think I have fixed it? Or I could tag you in the ticket to test it on staging, and then you could close it when you see it works (more work testing but sometimes nice to have 2 pairs of eyes)

**Comment by mhfowler** [comment]
maybe for now I can just close it, but can think about in the future if there's some way we want to get more people testing stuff (wouldn't even necessarily need to just be you). Especially if we accept more open source contributions
