### ISSUE TITLE
Change rep card photo size to make rep images look better

### ISSUE THREAD

**Issue by mhfowler** [CallParty/CallParty#165]
<img width="237" alt="screen shot 2017-03-03 at 12 00 51 am" src="https://cloud.githubusercontent.com/assets/1831536/23538847/7c4422ea-ffa4-11e6-968f-7f6ff3139863.png">

**Comment by kelseyah** [comment]
In the new Messenger Platform release:
_Generic template aspect ratio: Allows developers to specify “landscape” or “square” for image aspect ratio in generic template. Learn more._

That could help?

**Comment by jayres** [comment]
Square photos #292
