### ISSUE TITLE
as a potential partner/client, I'd like to kick the tires on a demo bot and explore all of the paths through the scripts

### ISSUE THREAD

**Issue by JoshData** [CallParty/CallParty#203]
It would be useful for demonstration purposes to have a bot account that continuously generates one-off campaigns for users so that they can see immediately what comes next after the onboarding script.

**Comment by kelseyah** [comment]
Hey @JoshData can you turn this issue title and content into a problem statement? that way we can figure out the best solution.

**Comment by JoshData** [comment]
As a potential partner/client (not an end user), one might like to be able to play with the bot and see what it does prior to deploying it. The problem is that if you start as a user on an existing bot, you can see the onboarding script but you can't see a campaign script until the bot is ready to give you a campaign.

**Comment by jayres** [comment]
Cool. We have expanded the documentation for the open sourcing considerably. I think it would be INCREDIBLY useful to have your feedback on that process. I personally am skeptical if it will be easy or difficult to get a sample bot up and running. 

Here is the guide as it stands: https://github.com/CallParty/CallParty/blob/master/CONTRIBUTING.md

I am going to close this issue but would super super appreciate any feedback or roadblocks you have with setting up your own instance. You or I can tag those as `open-source`.
