### ISSUE TITLE
If you send a message, instead of clicking a survey button, bot does not respond

### ISSUE THREAD

**Issue by mhfowler** [CallParty/CallParty#217]
e.g. if your callback path is `/calltoaction/readyResponse` (awaiting response for are you ready to call buttons)

and if you say something that isn't clicking one of the buttons, when you have this callback path, it does nothing. 

In the code it looks like this should log an error. So something weird is happening here.

If you give an unexpected response, it should probably say "I didn't understand that" and log what you said

**Comment by kelseyah** [comment]
bump

**Comment by oshoham** [comment]
@mhfowler the issue was a validation error creating the `UserAction`. the error didn't surface because of some weirdness around Promise error handling. switching to async/await revealed the error
