### ISSUE TITLE
Change mlab prod database to be production 

### ISSUE THREAD

**Issue by mhfowler** [CallParty/CallParty#237]
it is currently in sandbox mode

http://docs.mlab.com/production-guide/

**Comment by jayres** [comment]
This is a good idea but ultimately the shared db plan will be $15/month but a majority of the useful benefits require a dedicated plan ($180/month and up).
https://mlab.com/plans/pricing/

Maybe this issue should be closed and just put off until we have more funding or there is a concrete need to go into mLab's production clusters?

What do you think @mhfowler ?

**Comment by mhfowler** [comment]
@jayres sounds good, closing this issue
