### ISSUE TITLE
Investigate local number for William Schroeder (1308838185862019)'s district

### ISSUE THREAD

**Issue by kelseyah** [CallParty/CallParty#252]
"The D.C. Office goes to voicemail and the local office number is wrong. It is +1 (512) 469-6034. I called there and left feedback."

**Comment by kelseyah** [comment]
The number we're using is listed on Cornyn's website (956-423-0162) but maybe we should present a different one. @oshoham how hard is it to switch which local number gets populated?

**Comment by oshoham** [comment]
@kelseyah Currently it's pretty arbitrary which local number we use - we just send the first one we find in the database. We could come up with some way of selecting specific local numbers for specific representatives (e.g. we default to the first local number that we find, but there's the possibility of overriding that number on a rep-by-rep basis). Or we could come up with some way of presenting all of the possible numbers for a representative to users.
