### ISSUE TITLE
Bot replies overwhelmingly fast

### ISSUE THREAD

**Issue by cdrappi** [CallParty/CallParty#259]
Hey y'all, I think the work you have done is amazing. I think this has potential to be a major tool to get young people actively engaging with their reps. Thank you all for doing this.

One thing I noticed when chatting with the bot is that it sends messages very quickly. In fact, I felt a little bit spooked out as it sent multiple super long messages. It wasn't a pain to scroll up a bit, but I think an ideal chatbot would pace its message sending relative to how long it would take to read each message

I hope to contribute to this one day! This is inspiring

**Comment by cdrappi** [comment]
Btw! I read through your docs and felt here was the best place to submit the feedback. Please let me know if you'd prefer a different method

**Comment by mhfowler** [comment]
hey @cdrappi yes this is a great place to leave feedback, thanks!

This is something we thought of too but pushed back... we've probably normalized to it as this point lol -- but hearing it from you also makes me think we should think about doing this sooner

any feedback anytime appreciated

also if you ever would like to contribute / get the codebase running, happy to help and screenshare anytime. We're also having a meetup all day this thursday

**Comment by kelseyah** [comment]
++ everything @mhfowler said, thanks @cdrappi! 

We've done some research on this in #74 so I'm gonna go ahead and close this ticket so there aren't dupes – really appreciate it the note!
