### ISSUE TITLE
script / call creation form / update feedback

### ISSUE THREAD

**Issue by JoshData** [CallParty/CallParty#326]
Heya,

Amazing progress.

### Call Creation Form

The button on the campaign page says New Action but the header on the next page says New Call.

When setting up a call, it's a little confusing that there's a period in the script after the message field. It's more natural for the admin user to put the final punctuation in the message field since it's typically going to be one or more full sentences. I got two periods by mistake because I didn't notice it:

![image](https://cloud.githubusercontent.com/assets/445875/26631196/ef82dd40-45d7-11e7-8aea-f550243b1df9.png)

Since the Share Link comes in the script at the very end, it'd make more sense to move that field to the bottom rather than putting it after Issue Link.

The labels Subject and Task might be clearer if they're in the style of completing the sentence, i.e: the labels could be "You’re a constituent calling about..." and "I’d like [repType] [repName] to...". Otherwise it's hard to a) figure out which slot in the script these fields correspond to, and b) remember what sort of phrase I'm supposed to put in (I have to scroll up to see the script). For instance, natural values for Subject and Task in other contexts would be:

     Subject: Health Care Bill
     Task: Senator Votes No

But those would look funky in the script (because of the use of uppercase and the wrong sort of phrase for the task).

It might be helpful to be able to delete action and campaigns so long as no users have gotten any messages about it yet.

### Conversation

In the conversation, this part feels a little scary as a user:

> Always include a specific action you'd like the representative to take,

It sounds like the user is going to be expected to figure that out, when actually CallParty will tell them the specific action. It'd be friendlier to say something like "We'll give you a specific action to tell your representative to take".

Later, I got the senator's full name when the script in the admin said it would be repType repName:

![image](https://cloud.githubusercontent.com/assets/445875/26631529/66a77920-45d9-11e7-9116-4ff9e51e6f5b.png)

(It should ideally appear as "Senator Casey", with the title fully spelled out (since this is a script to be read) and without first/middle names or suffix.)

I'm thinking I should really swap in a different gif than the girl partying with a beer.

### Updates

When I make an update, the update is not going just to users who were participants in the campaign. I made a campaign with no actions and went straight to making an update (with no targeting), and all users are listed, and when I send, all users get the update. I think updates would make more sense if they only go to a) users who have received a prior message about the campaign, or better b) users who actually made a call on the campaign. (If they didn't make a call, they probably don't want to hear from CallParty again on the same subject.) Imagine that I send a campaign, then 1000 more users sign up, and then I send an update using borrowed targeting. The new 1000 users will get the update before they've been asked to make a call. 

(It could be useful to send a blast to all users about updates to CallParty, but that probably shouldn't be the default.)

### Analytics

"Constituents targeted" is confusing. The numbers that I'm expecting to see are:

a) how many user match the criteria that would get the message when I click "Send" (you could put that right inside the button's text, e.g. "Send to 2 Users")

b) how many users _actually got_ a message about the call, so that I can compute a conversion rate 

Same with updates.

Does "calls made" include both "talked to a staffer" and "left a voicemail" and exclude "something went wrong"?

It would also be really helpful to have some analytics on the top-most page:

a) how many users total are connected (i.e. users that would be targeted without any segmentation)

b) how many calls have users been asked to make across all campaigns

c) how many calls did users report making across all campaigns

And b & c per-campaign in the campaign table, and per-action in the conversations table on campaign pages.

**Comment by mhfowler** [comment]
@JoshData Same in response to your question: Does "calls made" include both "talked to a staffer" and "left a voicemail" and exclude "something went wrong"?

yes this is the intended behavior!

I'm working on your feedback now

**Comment by JoshData** [comment]
Thanks for clarifying.
