### ISSUE TITLE
Rep name display

### ISSUE THREAD

**Issue by mhfowler** [CallParty/CallParty#329]
Later, I got the senator's full name when the script in the admin said it would be repType repName:

(It should ideally appear as "Senator Casey", with the title fully spelled out (since this is a script to be read) and without first/middle names or suffix.)

**Comment by mhfowler** [comment]
@JoshData do you think in all places that repType repName it should appear like this in the script?

rep.repType rep.lastName ?

**Comment by mhfowler** [comment]
i think it might look good if in the full name is included in the card title
<img width="254" alt="screen shot 2017-06-06 at 4 22 13 pm" src="https://cloud.githubusercontent.com/assets/1831536/26834014/61c44a28-4ad4-11e7-9f95-3ba181403744.png">

and 'Representative Velazquez' is used everywhere else 

but happy to change to whatever y'all think is best @JoshData @kelseyah

**Comment by JoshData** [comment]
I think the "Representative Velazquez" format makes sense just when it's between quotes in the script (i.e. you're telling the user what to say, as in `Let them know "I'd like Representative Velazquez to..."`). Everywhere else "Rep. Nydia M. Velázquez" is probably best.
