### ISSUE TITLE
Wording of specific issue

### ISSUE THREAD

**Issue by mhfowler** [CallParty/CallParty#330]
In the conversation, this part feels a little scary as a user:
Always include a specific action you'd like the representative to take,
It sounds like the user is going to be expected to figure that out, when actually CallParty will tell them the specific action. It'd be friendlier to say something like "We'll give you a specific action to tell your representative to take".

**Comment by mhfowler** [comment]
@kelseyah would you like me to make this change also? or is there something you can both agree on without customization?

**Comment by kelseyah** [comment]
That works!

**Comment by kelseyah** [comment]
<img width="246" alt="screen shot 2017-07-06 at 1 19 00 pm" src="https://user-images.githubusercontent.com/3522339/27923821-b32323e0-624d-11e7-890e-98e89fd5ac26.png">

**Comment by JoshData** [comment]
:+1:
