### ISSUE TITLE
Change gifs

### ISSUE THREAD

**Issue by mhfowler** [CallParty/CallParty#332]
"I'm thinking I should really swap in a different gif than the girl partying with a beer."

**Comment by mhfowler** [comment]
@kelseyah rather than customize the gifs between the two, maybe it will be simpler implementatino to just change this gif to something you and josh are ok with?

**Comment by kelseyah** [comment]
Probably fine for short term but there likely won't be something that works for every group that uses this. I'll do some searching!

**Comment by kelseyah** [comment]
![yay](https://user-images.githubusercontent.com/3522339/27925068-6bfbcbb2-6251-11e7-9f66-1007f46c3eb6.gif)

**Comment by kelseyah** [comment]
how's that? cc/ @JoshData @mhfowler

**Comment by JoshData** [comment]
Excellent.
