### ISSUE TITLE
admin site is very slow

### ISSUE THREAD

**Issue by JoshData** [CallParty/CallParty#358]
admin.callparty.org has been very slow over about the last day (at least) and it isn't showing that any messages were sent for our last action (but it did --- I can see from the in-conversation reply that we've had 97 calls!).

**Comment by JoshData** [comment]
The admin site is 404ing now....

**Comment by mhfowler** [comment]
@JoshData thanks for reporting this !
Our google cloud free trial ran out and the servers went down. We just put them back online and re-deployed so the govtrack bot and admin page are up and running again

**Comment by mhfowler** [comment]
also v cool re: 97 calls. 

I'm also seeing this slowness on the admin site now :/ 

I'm going to look into it and see if I can speed it up

**Comment by mhfowler** [comment]
Hi @JoshData,
I was able to optimize a bunch of the slowness,
got the load time on the campaigns page down to 500ms from 17 seconds
and the load time on campaign detail down to 320 ms from 6 seconds

the campaignAction detail page is still kind of slow, it currently loads all of the users who it was sent to in one go. At some point we should make that page paginate the loading of users, I've made an issue for that here https://github.com/CallParty/CallParty/pull/364

**Comment by JoshData** [comment]
Thanks!
