### ISSUE TITLE
Put link into it's own message

### ISSUE THREAD

**Issue by JoshData** [CallParty/CallParty#365]
I got an email from a user saying that this link gave her a 404:

![image](https://user-images.githubusercontent.com/445875/30327980-00bbd772-979c-11e7-85aa-25f81c872e4f.png)

I have a feeling that on some platforms, automatic link detection is putting the period at the end of the sentence into the link, and that that's what caused the link to break for this user (but not others).

Do you think that's possible? If so, might be better to simply remove the period at https://github.com/CallParty/CallParty/blob/ee865c11baf607f0e44233ae11cb67294e7dc0fa/backend/app/conversations/callConvo.js#L73.

**Comment by mhfowler** [comment]
note: I will look into moving the link into its own message

**Comment by kelseyah** [comment]
@mhfowler did you get anywhere with this?
