### ISSUE TITLE
Export all interaction data

### ISSUE THREAD

**Issue by JoshData** [CallParty/CallParty#371]
Until there's a dashboard that answers every data question, it would be helpful to be able to export basically all of the data so we can run our own analysis.

One really helpful export would be a CSV file with columns: date, campaign, action, user, target (i.e. rep), did_they_make_a_phone_call. I'm curious if the calls are being made by the same set of users or if they are different users each time.

Another helpful export might be bot signups.

**Comment by mhfowler** [comment]
will be resolved by https://github.com/CallParty/CallParty/pull/384

currently it exports a .json of the format:
{
    userActions (just for your tenancy),
    users (just for your tenancy),
    campaignActions (just for your tenancy),
    representatives,
    committees,
    subCommittees,
  }

where each of these keys has a list of the rows  in that table

but now that the infrastructure is setup for data exports, we could also pretty easily modify the format of how this .json  is created, or what gets put into this .json... and use the same backend of sending a googleCloud temporary signed link with the data through email

**Comment by JoshData** [comment]
This would be great.
