### ISSUE TITLE
Put duplicate and delete icon buttons in campaign and call / message tables

### ISSUE THREAD

**Issue by kelseyah** [CallParty/CallParty#382]
Replace the "clone?" column with just a space for icons to take an action on a campaign / call / message.

Delete is dependent on delete functionality: https://github.com/CallParty/CallParty/issues/327

**Comment by kelseyah** [comment]
@mhfowler thoughts on these two icon options for "Duplicate" and "Delete"?

1: 
<img width="165" alt="screen shot 2018-02-17 at 4 39 33 pm" src="https://user-images.githubusercontent.com/3522339/36345859-39d7a1f8-1401-11e8-9a3d-c7781158c2d5.png">

2: 
<img width="163" alt="screen shot 2018-02-17 at 4 39 36 pm" src="https://user-images.githubusercontent.com/3522339/36345861-3dc5c9d4-1401-11e8-80fe-3a6512ddc0e0.png">

**Comment by mhfowler** [comment]
I think I like the top ones, but maybe instead of new should be the copy icon? https://www.google.com/search?q=copy+icon&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjw3-Tx9q3ZAhXB7IMKHUr9DBAQ_AUICigB&biw=1748&bih=925

**Comment by kelseyah** [comment]
i just wanted to use emojis 🙃

**Comment by kelseyah** [comment]
Dropped normal icons in slack bcause github doesn't like svgs
